import Navbar from '@/app/ui/navBar';
import { Metadata } from 'next';
import './styles.css';
export const experimental_ppr = true;
export const metadata: Metadata = {
  title: "Universidad CAECE - Mapa",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex h-screen flex-col md:overflow-hidden">
        <Navbar />
      <div className="flex items-center w-screen h-screen flex-col">{children}</div>
    </div>
  );
}